### ISSUE TITLE
[Suggestion] Interface selection

### ISSUE THREAD

**Issue by mrbesen** [cntools/cnping#67]
Would be cool, if you could specify the interface to use. like normal ping where you can do `ping -I wlan0 1.1.1.1`

**Comment by dreua** [comment]
At least on linux that should be easily possible: [c - bind socket to network Interface - Stack Overflow](https://stackoverflow.com/questions/14478167/bind-socket-to-network-interface)

One thing to investigate though is if that actually needs root permissions *and* `CAP_NET_RAW`. The top answer says so but lets hope this is incorrect and we can make it work with capabilities only. (Running cnping as root [messed with Wayland in the past](https://github.com/cntools/cnping/issues/35) and probably still does. That's why we went with `CAP_NET_RAW` only back then.) 

I probably won't work on this in the foreseeable future I'm happy to help/guide you if you want to start hacking!

Out of curiosity: What is your use case? VPNs?

**Comment by mrbesen** [comment]
In my case i have more than one connection to the internet (ethernet and mobile) and sometimes the ethernet connection breaks. So when i wait for the ethernet connection to come back up i would like to use cnping to monitor the ethernet interface. But of cause cnping chooses the working mobile connection and is not really helpfull. I guess VPN-User or VM-Hosts may use this feature too.

**Comment by dreua** [comment]
Are you interested in working on this?

**Comment by cnlohr** [comment]
@mrbesen that does sound like a preeettyy cool feature to have... It could exist if you make it exists.  We can test and help.

**Comment by dreua** [comment]
Closed via 0f821852b2f05632429577c5b363a51017977f9b

Thank you @mrbesen ! :100:
