### ISSUE TITLE
Makefile all multiple definitions

### ISSUE THREAD

**Issue by comfix** [cntools/cnping#72]
Won't build on Linux because `all` is defined multiple times in Makefile
Suggestion make one `windows` and the other one `unix`

**Comment by dreua** [comment]
You can just `make cnping` for linux in case that wasn't obvious. You probably don't want searchnet.

I guess for me and @cnlohr this definition of `make all` is the most convenient, since he recently added `all` I'll leave the decision to him.

Okay, now I realize that we do have two definitions of all but that doesn't make the build fail (at least not for me - you probably don't have the cross compiler for windows installed). Should be fixed anyway, that's true. Thanks for bringing it up!

**Comment by dreua** [comment]
Could also be #73 or that your build system actually does not get along with multiple definitions. Now I'm curious what the actual error / message is.

**Comment by cnlohr** [comment]
Yeah, "is defined multiple times in Makefile" makes me wonder if there's some weird merge issue going on.

**Comment by comfix** [comment]
I had the same issue as #73 but fixed it myself because I thought my repository just broke itself on fast-forward.

Yes, as @dreua said I don't usually compile for windows so I don't have cross compilers installed and it aborted on the same step every time (windows).

Its strange I just experimented a little bit and now this happens:
```unix
$ cat Makefile
all :
	echo "test1"
test :
	echo "test2"
all :
	echo "test3"
```
and the resulting make:
```
$ make all
Makefile:6: warning: overriding recipe for target 'all'
Makefile:2: warning: ignoring old recipe for target 'all'
echo "test3"
test3
```

This is at least I would think how multi-definition should affect this Makefile, but why it doesn't do this for the one here I don't have clue.

Thanks for the quick answer/s, really appreciate it! I don't know what happened yesterday that I opened this "unspecific" issue. Sorry for that

**Comment by cnlohr** [comment]
So good to close issue?

**Comment by dreua** [comment]
@cnlohr we should really delete one of the two `all` definitions. You added one in your latest commits, probably because I moved the old one down to the Linux section and you didn't see it. 

Which one would you like to keep?

https://github.com/cntools/cnping/blob/master/Makefile#L5-L34

**Comment by cnlohr** [comment]
I thought I just checked it out and that wasn't there.  DEFINITELY the first one.  Keep first.  I will do the delete.

**Comment by cnlohr** [comment]
I'm so sorry.  It's fixed now.

**Comment by dreua** [comment]
No worries, seems like we both had problems spotting duplicate ALL definitions today :laughing:  For me the problem was looking only at the commit diff instead of the whole file :see_no_evil: Thanks for fixing :+1: 



> This is at least I would think how multi-definition should affect this Makefile, but why it doesn't do this for the one here I don't have clue.

@comfix To me, multiple definitions sound much like undefined behavior and potential trouble. Not sure if this is defined somewhere and consistent across make versions and architectures so without good reason and proper research I'm sure it is better to just go with one definition. Thanks again for bringing this up :+1:

**Comment by comfix** [comment]
Sounded like undefined behavior for me as well, that's why I checked it.
Thank you really much guys!
