### ISSUE TITLE
Should we link to OpenGL?

### ISSUE THREAD

**Issue by cnlohr** [cntools/cnping#77]
I'm not sure what's appropriate behavior on X11, if we should setup rawdraw to use GLX or not.  I think we should.

The reason I'm thinking about this is because the CI build is currently failing.

@dreua do you have an opinion here?

**Comment by dreua** [comment]
CI was missing dependencies for OpenGL, fixed in 33992c3a2c6256abf2215d6432472ec5eca44303, [build is now passing](https://travis-ci.com/github/cntools/cnping/builds/181946605).

I don't know what is appropriate behavior here or not, but the current master works for me and I'm fine with leaving it like this. Do you mean we need to change anything else or is this done with the fixed CI?

**Comment by dreua** [comment]
I think we switched to OpenGL and should stay there for performance reasons: I just ran an older version and it uses less CPU for cnping (1 % of one core) but it causes Xorg to max out on CPU usage (100%). The current version is around 13 % CPU for cnping but no visible effect on Xorg (and my laptop stays silent).

**Comment by dreua** [comment]
Oh, are we talking about Xlib VS OpenGL or OpenGL VS GLX here? All I said was assuming the former, just learnt that GLX is a thing.

**Comment by cnlohr** [comment]
I'm not sure... I don't understand the distinction.  I thought GLX was *how* you open an OpenGL context in X.

**Comment by dreua** [comment]
Alright, never mind me digging up details that we shouldn't worry about. So we were talking about the same thing, agree that we prefer OpenGL/GLX and I'd say its fixed and this can be closed now, would you agree or is there anything else to discuss or do?

**Comment by cnlohr** [comment]
No closed.  Sorry forgot about this issue.
